# D96 · 契约欠债:证书/配对切片 13 条还清 · 两处缺陷收掉 · 欠债表机制补上「服务端半边不在 GPU 那个文件里」这一格

> 车道:V4 契约欠债 · 证书/配对切片(worktree `../.localAI-v4`,分支 `v4/contract-pairs-cert`)
> 日期:2026-08-06 · 状态:**待第 0 条车道取号并入**
> 前置:**D92**(垂直切片 + 成对断言硬前置)· **D93**(证书生命周期,本块上一轮)· **D95**(欠债表本身)
> 以 `python 90-ops/gate/check_contract_pairs.py` 那张表为准,本包不复写它的内容。

---

## §0 结论先给:**DEBT 23 → 10**

```
=== contract-pairs: TOTAL=27 PAIRED=17 DEBT=10 ===
  === 契约配对元规则:173 PASS · 0 FAIL ===
```

[证书/配对切片] 那 13 条**全部还清**;剩下的 10 条是 [GPU/租约切片] 4 条 + [未分配] 6 条,不归本车道。

---

## §1 ★★★ 动手前撞到的那件事:**欠债表的机制表达不了这 13 条**

这一条必须写在最前面,因为它决定了本车道**动了 `90-ops`**(而那是纪律里的禁区)。

`check_contract_pairs.py` 判 `paired` 的方式是:契约号(cid)同时出现在

- `_PEER_FILE = "10-core/gateway/test_gpu_broker.py"`(**写死**)
- `_CLIENT_PIN_FILE = "20-client-win/app/Selftest.cs"`

而本切片这 13 条的服务端半边是 **lan-edge(C#)**。`test_gpu_broker.py` 是 Python、
打的是 FastAPI 网关的 TestClient —— 它**结构上**测不了 lan-edge 的任何一条响应。

⇒ 照原样,唯一能把这 13 条标成 `paired` 的办法是**往 GPU 那张表里塞 13 个字符串**。
而那张表的循环是 `if _cid not in _observed: continue` ⇒ 塞进去的条目会**静默跳过**,
变成「有契约号、没有断言体」——**正是 D95 明写要防的「写着有防护、实际没有」**。
所以那条路被排除掉了,不是因为麻烦,是因为它会造出这套机制存在的理由本身。

**⇒ 已就此单独请示,用户裁定:最小改检查器。** 本包 §4 是那次改动的完整记账。

---

## §2 13 条怎么还的

### 2.1 形状登记表扩到 17 条(`10-core/identity/WireContracts.cs`)

D93 那轮只登记了 4 条。本轮补到 17 条(13 条路由 + 2 条**数组元素**子形状 + 1 条 **409** 失败分支 + 1 条文本契约)。
它仍然被 **lan-edge / transport / 客户端三个 csproj 同时编译** —— 期望值只有一份,它没法跟自己分家。

**两处「单字段冒充成对」按表里点名升级成键集合:**

| 路由 | 原来钉的 | 现在 | 为什么单字段不够 |
|---|---|---|---|
| `/pair/enroll` | 只有 `sasWordlistVersion` | 6 键全集 | `caCert`/`serverNonce`/`requestId` 任一改名 ⇒ SAS transcript 算不出来 ⇒ 客户端把它报成**中间人攻击**(一个自信且破坏性的结论) |
| `/identity/renew/complete` | 只有 `changed` | `{ok, changed}` | `ok` 是"这次切换成没成"的唯一信号,改名照样全绿 |

**两处如实登记、不硬凑:**
- `/pair/complete` 的应答**不是 JSON**,是一行文本 `active` ⇒ 登记成文本契约。
  给它编一个空键集合会让「顶层键恰好是这一组」变成**恒真**(空集恒等于空集)。
- `/admin/devices` 与 `/admin/pairing/pending` 的承重字段全在**数组元素**那一层
  ⇒ 顶层与元素**两层都登记**。只钉顶层的话 `deviceId` 改名照样全绿,而 A1 的病灶正是"字段藏在下一层"。

### 2.2 服务端半边:lan-edge 自检的「D96 丁」节 —— **真 HTTP**

★ 为什么不在进程里调 `pairing.Enroll(...)`:那拿到的是 C# 对象,证明不了
「序列化出去之后那个 JSON 长什么样」,而缝恰恰在序列化那一层。

★★ 顺带交付了一件本来没有的东西:**配对四条路由的 HTTP 全流程此前从没被端到端跑过**。
`ClientTransport.Pair` 里那段注释记着 2026-08-04 的实测「图形界面这条配对路径**从来没走完过**」,
而当时没有任何断言拦得住它。现在 enroll → status → 批准 → status → claim → complete 全程真 HTTP + 真 mTLS。

### 2.3 客户端半边:两个文件,各在**真正跑得到那段代码**的地方

| 契约族 | 客户端半边落点 | 理由 |
|---|---|---|
| `/admin/*`(9 条含子形状) | `20-client-win/app/Selftest.cs` | 消费者是 `HubAdmin`,而它的解析已被提成**纯函数**,断言能拿真 JSON 喂真解析器 |
| `/pair/*` · `/identity/renew/*`(6 条) | `20-client-win/transport/Program.cs` | 那边有**真的测试 Edge**,能把 `Transport.Pair` 端到端跑完;放 Selftest.cs 只能测仿造品 |

★ 形状**由登记表生成**,不是手抄 JSON。手抄的话服务端把字段搬了家,这一半照样绿 —— 那就是 A1。

### 2.4 ★★★ `/pair/status` 的失败分支(表里单独点名的那条)

表上的注解是「握手失败会让设备**永远停在 provisioning**」。它的陷阱是:

> **三个键在每一种状态下都在,只是批准之前后两个的【值】是 null。**

⇒ **只钉顶层键集合完全挡不住它** —— 那条断言在 pending 和 approved 上都会绿。
而客户端(`ClientTransport.cs:224`)只在 `approved`/`certificate_issued` 跳出轮询,
随后**无条件** `claimNonce.GetString()!`。一旦跳出条件漂了,要么 NRE、要么拿 null 去算 challenge,
两种都表现为「配对走不完」,而主机侧那条设备记录**永远停在 provisioning**。

**⇒ 把「跳出集合」与「放弃集合」也做成登记表的一部分**(`PairStatusProceed` / `PairStatusAbort`),
两侧读同一份,并**两侧都覆盖三种状态**:

- 批准**之前**:键集合对、`status` 不在跳出集合里、两个字段的值**是 null**;
- 批准**之后**:`status` 落在跳出集合里、两个字段**都已是字符串**;
- **被拒之后**:`status` 落在放弃集合里(落不进去 ⇒ 客户端一直轮询到 5 分钟超时,而主机侧停在 provisioning),
  且**失败分支的键集合与成功分支是同一组** —— 这条断言本身就是"只钉键集合分辨不出它们"的证据。

---

## §3 那两条**不是欠债、是缺陷**的,实测前后

### 3.1 `/admin/devices` 与 `/admin/devices/revoke` 各有两个消费者

**改之前(实测确认,不是推断):**

| 路由 | 两处 | 实际状态 |
|---|---|---|
| `GET /admin/devices` | `HubAdmin.DevicesAsync`(DevicesView:912)· `HubClient.ParseDevices`(DevicesView:1366) | **两份独立解析器**,而且两份的宽容度不同:`HubClient` 那份用 `TryGetProperty` 逐个兜底 ⇒ 服务端改一个键名,它会**安静地**返回一列"名字是空的设备",看起来像"主机上没有别的设备" |
| `POST /admin/devices/revoke` | `HubAdmin.RevokeAsync`(:1327)· `HubClient.RevokeDeviceAsync`(:1381) | **两个调用方,零解析** —— 两个都不看应答体 ⇒ 一次失败的吊销与一次成功的吊销在界面上**长得一模一样** |

**改之后:**
- 解析**收拢到一处**(`HubAdmin.ParseDevices` / `HubAdmin.ParseRevokeBody`),另一处委派;
- `HubClient.ParseDevices` 认不出形状时**抛**,不返回空表(空表 = 一句看起来很有信息量的假答案,
  与 `PendingAsync` 那条 `(ok, list)` 纪律同源);
- 吊销的应答**真的被核对了**:`ok=false` 或 `generation` 不是正数都会记进 `LastError`。
  `generation` 是 `Store.Mutate` 落盘的凭据 —— 只看 HTTP 200 只能说明路由跑到了。

★ 两个返回值签名**一个字节没改**(`DevicesView` 不在本车道归属里,没碰它)。

### 3.2 顺带被同一处改动收掉的两件

- `WindowAsync` 现在读应答里**中枢自报的**窗口状态并记下 ——
  此前只能拿本地布尔猜,而那正是 `Selftest.cs:5923` 明令禁止的那件事;
- `ApproveAsync`/`DenyAsync` 现在解析 **409 的 `error`** ——
  此前只看状态码,界面只能写「中枢拒绝了」,而最常见的失败其实是"这条请求已经不是 pending 了"。

---

## §4 ★ 越界记账:改了 `90-ops/gate/check_contract_pairs.py`(纪律里的禁区)

**已单独请示并获裁定「最小改检查器」。** 改了四处,逐条说明:

| 改动 | 内容 | 对既有行为的影响 |
|---|---|---|
| ① 第 ③ 组 | 两半的文件改成**逐条可覆盖**:`meta.get("server_file", _PEER_FILE)` / `client_file` | 不写覆盖的条目**一个字节没变** |
| ② 第 ④ 组 | 双向对拍**收窄到 server_file 仍指向 GPU peer 的那些** | GPU 那一族的双向对拍**一条没松**;收窄的是范围不是判据 |
| ③ 第 ④ 组 | **新增两条**:对拍范围非空(收窄不等于清空)· 被排除的逐个交代得出去处 | 净增护栏 |
| ④ | `_EXPECTED_DEBT` 23 → 10 | 表只许变短,这个数跟着变短 |

**★ 为什么②必须收窄**:不收窄的话,这 13 条会被要求"契约号也出现在 GPU 那个 Python 文件里",
而唯一能满足它的做法是往那张表里塞没有断言体的字符串 —— 见 §1。
**★ 为什么③是必需的**:收窄本身可能悄悄把**所有**条目排除掉,而"空集 == 空集"在那两条集合判据里
与"完全一致"长得一模一样(与"零命中判红"同款教训)。所以收窄这件事本身也要被钉住。

⇒ **请 V3 复核这四处**。本包 §7 有给 V3 的移交草稿。

---

## §5 门禁数字 · 断言数 · 红测

| 套件 | 前 | 后 |
|---|---|---|
| `check_contract_pairs.py` | 119 PASS(**DEBT=23**) | **173 PASS**(**DEBT=10**) |
| lan-edge selftest | 33 | **69**(+36) |
| transport selftest | 69 | **83**(+14) |
| 客户端 selftest(Debug 量) | 1939 | **1996**(+57) |
| identity 1/2/3/4/5 | 11/15/42/14/57 | 不变 |
| **门禁合计** | — | **PASS=1839 FAIL=0,√ 通过** |

**净增断言 +161 条**(lan-edge +36 · transport +14 · 客户端 +57 · 契约元规则 +54)。
其中**跨语言成对断言 34 条**(13 条路由 × 两半 + 4 条子形状/失败分支 × 两半),
**元断言 4 条**(两侧各"登记表每条都要被核对过" + 两个方向的条数对拍),
**反向断言 20 条**(少任一个键 ⇒ 判失败 / 零条目判红 / 恒真判据的反向)。

> ★ 门禁合计与上一轮(3379)**不是同一量程**:这是 worktree,`client --selftest` 没有产物没跑
> (V3 已把它从"红"改成"记进覆盖账的没跑"栏)。客户端那 1996 是本车道手工在 Debug 产物上跑的。

### 红测(每条护栏都看见过一次红)

| # | 动作 | 结果 |
|---|---|---|
| 1 | 服务端 `/admin/devices` 的**数组元素**里悄悄多一个键 | **恰好 1 条红**,消息直接打出病因:`实际 [… redTestKey …] / 登记 […]` |
| 2 | 把 `CONTRACT:cert.pair.status` 从 `transport/Program.cs` 里**全部拔掉** | **恰好 1 条红**,且它去找的是 `transport/Program.cs` ⇒ **证明 `client_file` 覆盖真的生效**,不是写了没用 |
| 3 | (**非人为,顺手抓到的**)三条 D93 时代的服务端钉子消息里没有契约号 | 检查器当场 **3 条红**,逐条点名"哪个文件里找不到哪个契约号" —— 这是这套机制的正向证据 |

★ 三次都用**文件备份**还原(不是 `git checkout` —— ASSERTION-PITFALLS 第 2 条),并逐个核对 SHA-256 一致。

★★ **红测 2 顺带暴露了这套机制一处已知边界**:第一版红测只把**一处**契约号改名,检查器**照样绿** ——
因为同一个文件里还有第二处提到它。这与 D95「明写不覆盖」第 ② 条完全一致
(判据是"契约号在不在",断言体被删空只留注释看不出来)。**如实记在这儿,不当成缺陷,也不假装它不存在。**

---

## §6 没做的,和为什么

1. **剩下 10 条欠债没动** —— [GPU/租约切片] 4 条归 V5,[未分配] 6 条等第 0 条车道指派。本车道只领了这 13 条。
2. **`client --selftest` 没进门禁** —— worktree 里没有构建产物(已知形状,按指示不去修),
   如实记在覆盖账。★ 那 +57 条客户端断言**在门禁上仍是零覆盖**,并入主树后须补跑一次。
3. **没碰 `DevicesView.cs`** —— 不在本车道归属里。两个返回值签名因此保持不变,
   缺陷是在 `HubAdmin`/`HubClient` 内部收掉的。★ 界面**还没有**把 `LastError` 里那句
   "吊销可能没生效"显示出来 —— 那一步归界面车道,已写进 §7。
4. **请求体方向仍不在范围内** —— D95 明写的范围就是"响应契约",本包没扩它。
5. **`/pair/complete` 只钉了文本值,没钉 Content-Type** —— 客户端只看状态码与正文,
   没有消费者读 Content-Type,钉它等于凭空造一条没人依赖的判据。

---

## §7 给第 0 条车道并入中央文档的**草稿**(本车道不改那四份)

### 7.1 `DECISIONS.md` 新条目

```
## 2026-08-06 · D96 · 契约欠债:证书/配对切片 13 条还清 · 两处双消费者缺陷收掉 ·
##                    欠债表补上「服务端半边不在 GPU 那个文件里」这一格

> 车道:V4(decision-packets/contract-pairs-cert-2026-08-06.md)。前置 D92 / D93 / D95。

### 裁定① DEBT 23 → 10:证书/配对切片 13 条全部成对

形状登记表(10-core/identity/WireContracts.cs)扩到 17 条,三个 csproj 同时编译;
服务端半边在 lan-edge 自检走**真 HTTP**(顺带把配对四条路由的全流程第一次端到端跑通 ——
2026-08-04 实测过"图形界面这条配对路径从来没走完过",当时没有任何断言拦得住);
客户端半边分落 Selftest.cs(/admin/*)与 transport/Program.cs(/pair/*、/identity/renew/*),
各在真正跑得到那段代码的地方。

### 裁定② 两处「单字段冒充成对」升级成键集合

/pair/enroll(原来只钉 sasWordlistVersion)与 /identity/renew/complete(原来只钉 changed)。
单字段挡不住别的键漂移,而这两条路由上"别的键"是承重的:前者漂了会把一次正常配对
报成中间人攻击,后者漂了看不出切换成没成。

### 裁定③ /pair/status 的失败分支必须两侧都覆盖

三个键在每种状态下都在,只是批准之前后两个的**值是 null** ⇒ 只钉顶层键集合完全挡不住。
⇒ 把「跳出集合 approved/certificate_issued」与「放弃集合 denied/expired」也登记进契约表,
两侧读同一份,并覆盖 pending / approved / denied 三种状态。

### 裁定④ /admin/devices 与 /admin/devices/revoke 的双消费者缺陷收掉

前者曾有两份宽容度不同的解析器(改一个键名,其中一份会安静地返回"名字全空的设备表");
后者两个调用方都不看应答体(失败的吊销与成功的长得一模一样)。
⇒ 解析各收拢到一处;认不出的形状**抛**而不是返回空表;吊销核对 ok 与 generation。

### 裁定⑤ 欠债表的 paired 判据支持**逐条指定两半所在的文件**

原实现把服务端半边写死成 10-core/gateway/test_gpu_broker.py(GPU 车道的 Python 测试),
而证书/配对那一族的服务端半边是 C#。不改的话,唯一能标 paired 的办法是往那张表里
塞没有断言体的契约号 —— 那正是 D95 要防的「写着有防护、实际没有」。
⇒ 加 server_file / client_file 逐条覆盖(不写则行为不变);第 ④ 组双向对拍收窄到
仍指向 GPU peer 的那些,并**新增两条**钉住"收窄不等于清空"。_EXPECTED_DEBT 23 → 10。
★ 这一处动了 90-ops(V3 地盘),已单独请示裁定,请 V3 复核。

门禁 PASS=1839 FAIL=0;契约元规则 119 → 173 PASS,DEBT 23 → 10。
净增 161 条断言(成对 34 · 元断言 4 · 反向 20)。红测 3 次,每次恰好红该红的那 1 条。
```

### 7.2 `STATE.md`

- 契约欠债 **23 → 10**;[证书/配对切片] 一栏**清空**;
- 剩余 10 条的归属要第 0 条车道拍板([未分配] 那 6 条);
- 新增待办:**并入主树后补跑一次客户端 Release 自检**(+57 条在门禁上零覆盖)。

### 7.3 给 **V3**(拥有 `90-ops`)

请复核 `check_contract_pairs.py` 的四处改动(本包 §4 有逐条记账)。
两处是**新增护栏**(对拍范围非空 / 被排除项交代去处),两处是机制扩展与债数。
★ 若你更想要另一种表达(例如把 peer 文件做成 per-lane 列表),本车道这版可以整体让路 ——
它满足的判据是"不塞没有断言体的契约号",怎么实现不重要。

### 7.4 给**界面车道**

`HubAdmin.RevokeAsync` / `HubClient.RevokeDeviceAsync` 现在会在吊销应答不对时写 `LastError`
(`ok=false` 或 `generation` 不是正数)。`DevicesView.cs:1327` 与 `:1381` 两处**还没有把它显示出来** ——
今天它仍然只看状态码。那两行归界面车道,本包没碰。
