# `/v1/sync/snapshot` 接上「上线 + 重连都拉」(V15 · 2026-08-08)

> 车道:**V15 · 接上 /v1/sync/snapshot**
> 用户裁定(2026-08-07):**接上**,不是撤掉。
> 实机证据:**副机开机拉不到主机已有的共享会话**。
> D 号:草案写 `D?`,并入那刻取号(当前最大 **D107**)。

---

## 0. 先把话说清楚:我修的是**三格**,不是"已复现并修好了那一格"

我**没有**在真机上复现过"副机开机拉不到"。所以本包不写「已修复」。

写得出的是这个:那句症状——**连接活着、`generation` 有值、界面说「已同步」,而这台机器上
一条共享数据都没有**——在今天的代码里**至少有三条路能走到**,而这三条现在都堵上了,
并且**每一条都从"不说话"改成了"会说话"**。

| # | 走到症状的那条路 | 此前 | 现在 |
|---|---|---|---|
| ① | **流根本没建起来**(网关刚起、中间那层把 SSE 缓冲住、握手抖一下) | 一条数据都拉不到,而唯一的对齐动作挂在这条流上 | 开流**之前**先走一次平的 `GET /v1/sync/snapshot` |
| ② | **首帧到了但 `Absorb` 抛了** | 整帧丢掉;补救动作挂在**下一帧数据**上,而下一帧要等**有人改东西**才会来 | 补救挪到 `data:` 分支**外面** —— 心跳(15 秒一次)也能把它救回来 |
| ③ | **首帧没吃下,却照样把本地那份推了上去** | 无条件推 ⇒ 墓碑没落地 + 本地旧数据回灌 ⇒ **对方删掉的东西在他那边复活** | `_pullFirst && !_needFullPull` —— 全量没吃下就不推 |

★ ①②的**表现完全一样**,而且都不报错。副机冷启动那句症状,落的就是这个形状。
★ 如果真机上仍然复现,那就是**第四格**——而第四格现在会自己说话:
界面多一行「★ 还没跟中枢对齐(拉全量没成)—— 这台机器上现在可能少了对方的改动」,
`LastError` 里有 HTTP 状态码,服务端扣下的东西在 `{state}/shared/withheld/` 里留着证。
**在此之前这一格在界面上一个位置都没有。**

---

## 1. V6 那份处置包错在哪一格 —— 不是"结论错",是**推理少了一步**

V6(`sync-snapshot-disposition-2026-08-06.md`)只把这条路由接在**流内丢帧**上,理由是:

> 「**重连**对齐不需要它 —— `/v1/sync/events` 首帧就是全量……
>   接成"重连也走它"就是把首帧全量那条路重复一遍,那种断言恒绿。」

**前半句是对的,而且我核过:服务端首帧确实是全量**(`gateway.py:1537` 的 `snapshot()`,
`since_rev=0`;`test_sync.py` 有一条断言钉着它)。

**少的那一步是:「服务端首帧是全量」≠「客户端手上有了那份全量」。**
中间隔着上表 ①②③ 三件会失败的事,而它们失败时**长得和成功一模一样**。
⇒ 「重连那条路没有洞」这句话,应当写成「重连那条路**在流建起来且首帧吃下**的前提下没有洞」。
那个前提正是要验的东西,不能当成已知条件。

★ 所以新加的这条**不是**重复路径:它跑在**开流之前**,恰恰是首帧永远盖不到的那一格里
唯一还能跑的东西。这也正是 `doctor.py` ⑦ 环和 `probe_sync.py` 当初挑它而不挑 SSE 的理由——
**一个平的 GET 在很多"长连接建不起来"的条件下仍然能成。**

---

## 2. 用户四条裁定,逐条落在哪

| 裁定 | 落点 | 判据在哪 |
|---|---|---|
| **上线拉一次全量** | `SyncClient.RunAsync`:`PullFullAsync(ct)` 在 `Transport.OpenStream` **之前** | `test_sync.py` ②:位置断言 + 零命中元断言 |
| **★ 断线重连也拉** | 同一处 —— 它在 `while (!ct.IsCancellationRequested)` **循环里面**,所以每次重连都重跑 | `test_sync.py` ②:「在重连循环里面(不是只在 Start 里跑一次)」 |
| **合并沿用 D86:后到的赢 + 保留被覆盖的** | **一个字没动** —— 拉回来的全量喂进**同一个** `Absorb`,合并规则仍在服务端 `put()` | 既有断言(第 2 节)原样跑;新增「喂的是同一个 Absorb」 |
| **★ 只拉家庭/共享,判据在服务端** | `sync_store.snapshot()` 现在**也过 `in_scope`** —— 见下一节 | `test_sync.py` ①:含**反向注入**(否则这道闸恒绿) |

---

## 3. ★★★ 服务端那条:范围判据此前**只在写那一侧**

D86 裁定①的原话是「只收家庭/共享的」。它落在 `put()` 里,**读那一侧一句都没问过**。
于是「只同步家庭/共享的」在**拉**的方向上是一句**推论**,不是判据。

而这不是理论风险,**有一条今天就能走到**:

> 共享会话被删(墓碑)⇒ `in_scope` 明写它的消息**从此拒收**(免得留孤儿消息)。
> **但已经在库里的那些消息照发不误。**
> 会话都没了,正文还在一帧一帧地往另一台机器上走 —— 而这类错误**没有撤销键**。

⇒ `snapshot()` 现在逐条过**同一个** `in_scope`。三条设计取舍,逐条写明:

1. **同一个判据,不另写一份** —— 两份会漂,而漂的那天写这侧绿、读这侧在漏,没有任何东西会红;
2. **墓碑必须放行** —— 它要是也被扣下,另一台就永远不知道这条被删了,删除又变成删不掉;
3. **扣下要留证** —— 从副机看,「扣下」和「丢了」长得一模一样(它就是少一条)。
   ⇒ 与「被覆盖的那一版存起来」同一条纪律:内存记一份(`withheld()`)+ 落一份
   `{state}/shared/withheld/{kind}-{id}.json`(**不抄记录正文** —— 被扣的往往正是私人正文,
   而它在同目录的 `{kind}.json` 里已经有一份,再抄一遍只是多一个副本)。

★ `counts` 一并改成报**这个端点真会发出去的条数**(过闸之后)。报库里的数会让
`counts 2 / data 1` 这种差额变成一种没人在看的少给,而 `doctor.py` 印的正是这个数字。

### ★ 这一条**没做**的事(不许读成"全解决")

**扣下 ≠ 撤回。** 一条已经同步过、后来变得不合格的记录(比如家庭待办被改成个人),
中枢从此不再发它,**但副机上那一份仍然在**。要真收回得发一条「撤回」记录,
而那等于**在另一台机器上删东西**,形状与墓碑同级、风险更高(墓碑至少是用户自己按的删除)。
⇒ 本车道**不做**,如实记在这儿。今天的效果是:**不再继续外流**,不是**追回**。

---

## 4. 改了什么(三个文件,逐处)

### `10-core/gateway/sync_store.py`
- `snapshot()`:逐条过 `in_scope`;`counts` 改为过闸后的条数;
- 新增 `_note_withheld()` / `withheld()`:扣下留证(同一条只留一次 —— 每帧都调,每帧写会把证据自己淹掉);
- 文件头规矩①改成「**只收**家庭/共享的,**也只发**家庭/共享的」。

### `20-client-win/app/Services/SyncClient.cs`
- `RunAsync`:开流**之前** `_needFullPull = _pullFirst = true;` 然后
  `if (await PullFullAsync(ct)) { _pullFirst = false; await ReconcileAsync(ct); }`
  —— **先拉后推**这条纪律原样保留,只是现在不依赖 SSE 首帧;
- `OnLine`:`if (_needFullPull) _ = Task.Run(() => PullFullAsync());` **挪出 `data:` 分支**;
  推的条件补上 `&& !_needFullPull`;Live 转换里**不再**重点标记(开流前已经点过,再点是白拉一遍);
- `PullFullAsync`:加**单飞闸**(三个触发点可能同时点它);
  ★ 回值判据改成**标记有没有真的清掉**,不是"HTTP 200 拿到了"——
  `Absorb` 解析失败会把标记重新点上,那种情况下回 `true` 等于告诉调用方"可以推了",
  而本机手上根本没有那份全量;
- `StatusLine()`:欠着一次全量对齐时**说出来**。

### `10-core/gateway/test_sync.py`
- 新增两节共 **31 条**断言(见下);
- D92 那节补上 `CONTRACT:sync.snapshot` 的**深度**复核(见第 6 节)。

---

## 5. 代价,如实写

1. **每次重连多一个 GET。** 客户端重连退避是 2→4→8→16→30 秒封顶,所以一台连不上的机器
   最多每 30 秒拉一次全量。读侧**没有额度维**(`sync_policy` 只对 `sync_write` 计额度,
   而且有一条断言钉着「读不占写额度」)—— 也就是说**这条路上没有闸**。
   家里两台机器的数据量下这没问题;写在这儿是因为它是一个**真的没人守的方向**。
2. **`snapshot()` 现在每帧对每条记录调一次 `in_scope`。** SSE 每次唤醒(推送、上下线、
   15 秒心跳)都会调 `snapshot(since_rev=…)`。家庭数据量(几百条)下是常数级噪声,
   但它**从 O(n) 的字典过滤变成 O(n) 次函数调用** —— 记账在此,不声称"零成本"。
3. **补救仍然只在"帧到达"时触发**(D37 ② 推送非轮询)。如果 `Absorb` 持续失败而数据又在变,
   每一帧都会点一次拉全量(单飞闸把并发收成一次,但**串行的重试没有节流**)。
   没有加退避 —— 加了就等于在这条路上引进一个定时器。**如实记着,不假装它有闸。**
4. **`test_sync.py` 现在跑约 2 分钟**(本车道多打一次 `/v1/sync/snapshot`,不新建 `TestClient`,
   所以没有再 +15 秒;V6 记的那条「三次 TestClient 生命周期约 45 秒」照旧成立)。

---

## 6. ★ 契约复核 —— 任务点名的那一条

`CONTRACT:sync.snapshot` 今天在 `90-ops/gate/check_contract_pairs.py` 里是 **paired**,
欠债 **1/30**。逐条核过:

| 要核的 | 结论 |
|---|---|
| 服务端半边(顶层键集合 `{generation,since_rev,data,counts}`) | **没变** —— 本车道**没有**往响应里加键(withheld 走内存 + 落盘,不上线),既有断言原样跑 |
| 客户端半边(`PullFullAsync` → `Absorb`) | **还在**,而且触发点从 1 个变成 3 个(上线/重连 · 断层 · 解析失败) |
| 欠债数 | 仍是 **1**(只剩 `GET /health`);`TOTAL=30 PAIRED=29 DEBT=1`,门禁 252 PASS · 0 FAIL |

**★★ 但它此前钉得不够 —— 这条路由的用途变了,断言要跟着变。**

顶层键集合在"只在丢帧时走一次"的年代够用。现在**副机冷启动的全部共享数据都从这里来**:
`data.sessions[i]` 少一个 `id`、或者 `data` 里整个少一个集合,**顶层键集合照样绿**,
而副机开机看到的是一片空白。⇒ 本车道把**消费者真正读到的那几层**一起钉了
(`since_rev==0` · `generation` 是数字 · `data` 三个集合一个不少 · 每条带 `id` 与 `rev`),
并配了「这次快照里确实有记录」的元断言(空表会让逐项断言静默变成零断言)。

### ★★★ 两处**必须移交**,因为它们在本车道禁区里

1. **`90-ops/gate/check_contract_pairs.py` 里那条 `note` 现在是错的。** 它写着:

   > 「用途**不是**重连对齐(重连那条路本来就没洞 —— `/v1/sync/events` 首帧就是全量),
   >   而是**丢一帧之后的补全量**。」

   今天起它**同时**是上线/重连的对齐路径。那份 note 是给下一个改这条路的人看的,
   **留着错的比没有更坏**。请 90-ops 车道改成:「V15 起三个触发点:上线/重连 · 断层 · 解析失败。」

2. **`20-client-win/app/Selftest.cs` 里 `CONTRACT:sync.snapshot` 的客户端半边钉错了位置。**
   它今天钉的是 `FrameContinues(0, 0)` —— 那是**断层判据**,不是"一份真的快照体能被解析出来"。
   在"只在丢帧时用"的年代这说得过去;现在这条路由承的是冷启动的全部数据,
   而**客户端能不能把它解析出来这件事,客户端那半边一条都没钉**。
   ⇒ 请客户端车道补一条:喂一份**服务端真实形状**的快照体给 `Absorb`(或抽一个可测的解析入口),
   断言三个集合都取得出、每条的 `id`/`device` 读得到。
   ★ 本车道**没有代改** —— `Selftest.cs` 不在边界内,而且 V12/V13 两条车道正在动它。

   > ★ 这两条合起来正是任务里那句「别让它从『钉着一条没人走的路』变成『钉错了』」——
   > 路现在有人走了,而**钉子的位置没跟着挪**。本包能钉的那一半(服务端深度)已经钉上,
   > 另一半在别人的文件里,**明写移交,不静默留着**。

---

## 7. 验收:单机能到哪一格,哪一格必须真机

验收原话:「副机**冷启动**后能看到主机已有的共享会话与家庭待办;个人待办**仍然看不到**。」

### ✅ 单机已经验到的(全部实测,不是推理)

| 验到什么 | 怎么验的 |
|---|---|
| 个人待办**发不出去** | `test_sync.py`:**反向注入**一条个人待办直接进库(绕开 `put`),`snapshot()` 扣下它 |
| 共享会话删掉后,它**已经在库里**的消息也发不出去 | 走**正常公开 API**(put→put→delete→snapshot),不用注入 |
| 墓碑仍然发得出去 | 同上一条的反面断言 |
| `counts` 不广告拿不到的数字 | 断言 `counts == len(data)` |
| 扣下**留了证、说得出理由** | `withheld()` + 留证文件存在 |
| 全量的 `since_rev==0`、三个集合一个不少、每条带 `id`/`rev` | 打真端点(`TestClient`)取真响应 |
| 客户端**拉的调用点在开流之前、在重连循环里** | 源码结构断言 + 括号深度判据 + 零命中元断言 |
| 客户端**补救不在 `data:` 分支里** | 括号配对:`if (_needFullPull)` 的下标 > data 分支的收尾 `}` |
| 客户端**拉失败就不推** | 源码断言 `_pullFirst && !_needFullPull` |
| 上面这些改动**没有踩坏 `Selftest.cs` 的位置断言** | 在本机把那 14 条位置断言**重放**了一遍(见第 8 节) |

### ⚠ 单机**做到了、但只做到一半**的那一格

**客户端 `--selftest` 本轮真的跑起来了 —— 而且是在 worktree 里。**

★ 「worktree 里客户端自检必然『没跑起来』」这句话**只对 `run-tests.ps1` 那一步**成立
(它找的是**打好包的** dist,而 `bin/` 不进 git)。
直接 `dotnet build` 再跑 `bin\Release\…\localai-client.exe --selftest` 是**能跑的**,
实测 **2120 PASS · 0 FAIL**;把 `SyncClient.cs` 换回 HEAD 版重建再跑,**也是 2120 PASS · 0 FAIL**
⇒ 断言条数一条没变(本车道确实没动 `Selftest.cs`)、也一条没被弄红。

**但它证到的仍然只有这些:** `Selftest.cs` 里针对同步的那些断言 ——
源码形状(位置/顺序/护栏)+ `ParsePush`/`FrameContinues`/各 Center 的合并行为。
**它没有、也不可能有**「真的发出 `GET /v1/sync/snapshot`、把真响应喂进 `Absorb`、
记录落进 Center」这条端到端断言 —— 那正是第 6 节移交给客户端车道的那一条。

### ❌ 单机**到不了**的两格 —— 逐格说清为什么

1. **副机 → 中枢那条链本身,Python 工具替不了。**
   `probe_sync.py` 自己的文件头写着原因,而那个原因是硬的:
   > 副机连中枢要 mTLS 客户端证书,而**证书私钥在 CNG 里不可导出**(D43/D44)—— Python 拿不到。
   ⇒ 副机侧的验收**必须用客户端界面做**。
   ★ 一个可以先做的降级检查:本车道核过 lan-edge 的 `MapFallback` 是**通用代理**
   (任意方法 + 任意路径 + 注入已验证指纹),`GET /v1/sync/snapshot` 走的是
   **和 `POST /v1/sync/push` 完全同一条**代理路径 —— 而后者副机今天已经在成功地走。
   ⇒ "这条 GET 在副机上会不会 404" 这个风险**结构上排除了**,但**不等于实测过**。

2. **「冷启动」这个条件本身。** 进程从零起、本地存档先读完、流还没建起来的那几秒 ——
   单机上没有第二台可以"关着机、再开机"。这一格**只能真机**。

### ★ 真机验收怎么跑(两台,按顺序)

```
主机: python 90-ops\debug\probe_sync.py --watch 120
```

```
副机: 关掉客户端 → 主机上新建一条家庭待办 + 一个共享会话 → 再开副机客户端
```

看三件事:① 副机界面上出现那条家庭待办与那个共享会话;
② 副机上**个人**待办栏里没有主机的私人条目;
③ 副机同步状态那一行**不出现**「还没跟中枢对齐」。
★ ③ 是新加的:它为真就说明拉全量没成 —— **这一格此前在界面上没有任何位置。**

---

## 8. 红测 —— 每条新护栏都亲眼见过红

★ 一律**字节备份还原**,不用 git;每条还原后核 SHA(**9/9 逐字节一致**)。

| # | 方向 | 改坏什么 | 结果 |
|---|---|---|---|
| R1 | 红 | 读侧范围闸整个拿掉 | 红 7 条,含「读侧把它扣下了」 |
| R2 | 红 | 留账改成空操作(扣下变静默) | 红「扣下**不是静默的**」 |
| R3 | 红 | 会话墓碑也被读侧闸扣下 | 红「墓碑本身仍然发得出去」 |
| R4 | 红 | `counts` 改回报库里有几条 | 红「counts 不广告拿不到的数字」 |
| R5 | 红 | `data` 里**多发**一个集合 | 红「三个集合一个不少」 |
| R6 | 红 | 补全量的触发**挪进** `data` 分支(外面那处删掉) | 红「在 data 分支**外面**」 |
| R7 | 红 | 拉全量挪到开流之后 | 红 3 条,含「开流之前」 |
| R8 | 红 | 全量没吃下照样推 | 红「全量没吃下就不推」 |
| G1 | **绿** | `data` 分支里**多加**一处触发(冗余,不算坏) | **仍然全绿** —— 判据没有紧到把没坏的判红 |

### ★★★ 三条没按预期走的,以及它们各自暴露了什么

1. **R6 第一版没红 —— 而它牵出了判据本身的一个真假绿。**
   第一版红测是"往 `data` 分支里**加**一处触发",外面那处还在 ⇒ 行为没坏 ⇒ **本来就不该红**。
   但顺着"为什么没红"查下去,摸到了判据的真问题:我写的是
   `rfind("if (_needFullPull)") > data 分支收尾`,而 `rfind` 扫的是**整份文件** ——
   判词说的却是"**OnLine 里**那处在分支外面"。
   哪天有人在别的方法里也写一句同名判断,而 OnLine 里那处被挪了进去,**判据照样绿**。
   ⇒ 收紧成:先切出 **OnLine 方法体**,再用 `finditer` 看**全部**出现位置。
   然后 R6 改成真的"挪进去"(外面那处删掉)⇒ 红;G1 保留"多加一处"作**反向**用例 ⇒ 绿。
   > ★ 教训写进 §10.3 的补注:**红测没红的时候,先别急着改红测** ——
   > 先问判据问的是不是判词说的那件事。

2. **R3/R5 第一版把整套**打崩**了(KeyError,没有汇总行),而不是判红。**
   R3 把全部墓碑都扣下 ⇒ V6 那条既有断言先 `_rec["t1"]` KeyError;
   R5 直接不发 `messages` 那个键 ⇒ 后面每一处 `["messages"]` 都炸。
   ★ **崩溃也是信号,但形状不对**:运行器只看到"没有汇总行",看不出是哪条没守住
   (ASSERTION-PITFALLS 第 6 条那族)。⇒ 两条都收窄成只碰一处,让红精确落下。
   ★ **如实记账:「`data` 里少发一个集合」这个方向,本套件今天的表现是崩溃而不是判红。**
   R5 验的是同一条断言的另一个方向(多一个键)。没有把它写成"两个方向都干净地红过"。

3. **另有一次自伤,与护栏无关但值得记:** 用 Python 的 `write_text` 做了一次全文替换,
   把 `SyncClient.cs` / `test_sync.py` 从 LF 悄悄换成了 CRLF ⇒ 多行锚点全部失配、
   `git diff` 里整份文件都变了。而用 `read_text` 写的锚点预检**说一切正常**
   (它把 CRLF 归一化了)⇒ **校验绿、真跑红**。已还原为 LF 并复核 `git diff --stat`。

**★ 另外重放了 `Selftest.cs` 里钉 `SyncClient.cs` 源码形状的那 14 条位置断言**
(`ReconcileAsync` 在 `Link = SyncLink.Live` 之后 800 字符内 · `Absorb(line[6..])` 在
`ReconcileAsync())` 之前 · `_pullFirst` 还在 · 裸 `Changed?.Invoke()` 只许 1 处 ·
推失败分支不清队列 …)—— **14 PASS · 0 FAIL**。
★ 这一步本来是为"worktree 里跑不了客户端自检"准备的替代品;**后来发现自检其实跑得了**
(见第 7 节),所以它现在是**冗余的**一层。留着不删:它跑一次两秒,而那几条是位置断言,
挪一行就红。

---

## 9. 实测数

- **worktree 门禁 `run-tests.ps1 -Full`:`PASS=2114 FAIL=0` · 跨进程契约欠债 `1 / 30`。**
  ★ 2114 **不能**和 STATE 里那个 4197 比:worktree 形态下记忆那 11 个套件(要 PG/venv)
  与 `client --selftest`(要出包)**没跑**,门禁把它们逐条列成"没跑"而不是当成过。
  ⇒ 全仓总数请由第 0 条车道在 main 上实跑,本车道**不代报**那个数。
- `test_sync.py`:**153 PASS · 0 FAIL**(本车道之前 **120** ⇒ **新增 33 条**);
  其余 22 个 Python 套件 + 9 个 dotnet 套件**逐个对过,一个没变**;
- `90-ops\gate\check_contract_pairs.py`:**252 PASS · 0 FAIL** · `TOTAL=30 PAIRED=29 DEBT=1`
  (与收工要求一致:欠债仍是 **1/30**,**一条都没多**);
- 客户端 `dotnet build -c Release`:**0 错误**(10 条警告全是既有的,`SyncClient.cs` 里一条都没有);
- 客户端 `--selftest`:**2120 PASS · 0 FAIL**。
  ★ 并且做了**对照**:把 `SyncClient.cs` 换回 HEAD 版重建再跑 —— **也是 2120 PASS · 0 FAIL**。
  ⇒ 断言条数**一条没变**(本车道没动 `Selftest.cs`)、也**一条没被弄红**。
  ★ 这是本轮的一个副产物:**worktree 里客户端自检是跑得了的**(见第 7 节),
  跑不了的只是 `run-tests.ps1` 那一步。
- `Selftest.cs` 位置断言重放:**14 PASS · 0 FAIL**;
- 红测:**9/9 按预期**(8 红 + 1 反向绿),每条还原后逐字节一致。

---

## 10. 给第 0 条车道并入中央文档的**草稿**(本车道不改那四份)

### 10.1 `DECISIONS.md` 新条目

```
## 2026-08-08 · D? · /v1/sync/snapshot 接上「上线 + 每次重连都拉全量」·
##                   范围判据补上【读】那一侧

> 车道:V15(decision-packets/sync-snapshot-pull-on-connect-2026-08-08.md)。
> 前置 D86(内网同步三条裁定)· D92(跨进程契约成对)· D37 ②(推送非轮询)。
> 用户裁定 2026-08-07:接上,不是撤掉。

### 裁定① 上线与每一次重连,先拉一次全量再开流

拉全量此前的唯一触发点是「收到一帧、发现断层」⇒ 对齐整个建立在 SSE 那条流上。
流建不起来 / 首帧没吃下时,这台机器一条共享数据都拉不到,而它不报错、不掉线、
界面照样说「已同步」。⇒ 调用点挪进重连循环、放在 OpenStream 之前。
★ 顺序仍是先拉后推(D86 墓碑);拉不成就不推,标记留着下一帧补。

### 裁定② 全量没吃下就不推

此前 `_pullFirst` 是无条件推的,而 Absorb 的 catch 真的会走到 ——
墓碑没落地 + 本地旧数据回灌 = 对方删掉的东西在他那边复活。

### 裁定③ 范围判据在【读】那一侧也过一遍,扣下要留证

D86 裁定①此前只落在 put()。已经在库里的东西发出去之前没有人再问一句 ——
共享会话删掉之后,它那些消息照发不误。⇒ snapshot() 逐条过同一个 in_scope;
墓碑放行;扣下的记进 withheld() 并落 {state}/shared/withheld/。
★ 扣下 ≠ 撤回:副机上已有的那一份仍然在。本轮只做到「不再继续外流」。
```

### 10.2 `STATE.md` 增量(★ 数字以第 0 条车道**实跑**为准,本行只给构成)

```
· 全仓基线:唯一变的套件是 10-core\gateway\test_sync.py:120 → 153(+33)。
  ★ 请在 main 上实跑取数,**不要**拿 4197 + 33 算 —— 本车道在 worktree 里量到的是
    PASS=2114(记忆 11 个套件与 client --selftest 在这个形态下没跑),两个数不可比。
    「算出来的基线」正是这份文档反复要防的那种数字。
  ★ 客户端 --selftest **条数不变**:Selftest.cs 一个字节没改,
    而且本轮做了 HEAD 版对照重建,两边都是 PASS=2120 FAIL=0。
  ★★ 这个数字请以第 0 条车道**实跑**为准:STATE 里那行 1981 是 V6 期的,
    本机今天(worktree、直接跑 exe)量到的是 2120 —— 中间几条车道加过断言。
· 跨进程契约:总数 30 不变 · 已成对 29 不变 · **欠债仍是 1/30**(只剩 GET /health)。
  ★ CONTRACT:sync.snapshot 的服务端半边**加深了**(从顶层键集合加到
    since_rev/generation/三个集合/每条 id+rev),但那不改变"成对"的计数。
```

### 10.3 `ASSERTION-PITFALLS.md` 建议补注(★ 本车道**没改**那份文档)

给第 3b 条(「判词说『每一个』,判据是一份写死的名单/位置」)补一个**新形态的实例**:

> **搜索范围写得比判词宽,`rfind` 就会替你找到一个"看起来对"的答案。**
> 本车道第一版判据是「`rfind("if (_needFullPull)")` 的下标 > data 分支的收尾」——
> 判词说的是"**OnLine 里**那处触发在分支外面",判据扫的却是**整份文件**。
> 哪天有人在别的方法里也写一句同名判断,而 OnLine 里那处被挪进了分支,
> **`rfind` 会找到文件末尾那个,判据照样绿,而洞已经回来了。**
> ⇒ 两条收紧:① 先把**方法体**切出来再找;② 看**全部**出现位置(`finditer`),
> 判词是"至少有一处在外面"就照着写,不要用"最后一处"去近似它。
> ★ 这条是**红测逼出来的**:第一版红测往分支里加了一处,判据没红 ——
> 当时那个绿其实是对的(多一处不改变行为),但顺着它一查,就摸到了上面那个真的假绿。
> ⇒ **红测没红的时候,先别急着改红测**,先问判据问的是不是判词说的那件事。

---

> 出处:2026-08-08 · V15 车道 · 全部数字为本车道实测。
